
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pushkin_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: pushkin_test
  pool: 5
  username: postgres

development:
  adapter: postgresql
  encoding: unicode
  database: pushkin_production
  pool: 5
  username: pushkin
  password: pushkin
